# Generated by Django 3.2.7 on 2021-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20211010_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_link',
            field=models.URLField(max_length=255),
        ),
    ]
